In [ ]:
pip install faker_vehicle

In [1]:
import random
import datetime
import tqdm
import decimal

In [2]:
from faker import Faker
from faker_vehicle import VehicleProvider

In [3]:
fake = Faker()
fake.add_provider(VehicleProvider)

In [4]:
import json 
import pymysql

pymysql.install_as_MySQLdb()

with open('cred.json') as f:
    creds=json.load(f)
    
    
connection_string = "mysql://{user}:{password}@{host}".format(**creds)

In [5]:
%load_ext sql
%config SQLMagic.autocommit=True
%sql $connection_string

In [6]:
import datajoint as dj
schema = dj.schema('black_squares_llewis')

Connecting llewis1@db.ust-db.link:3306

In [ ]:
%%sql 

USE black_squares_llewis

In [ ]:
%%sql 

SHOW TABLES

In [ ]:
%%sql 

SHOW DATABASES

In [ ]:
%%sql 

SHOW TABLES

In [9]:
Car.drop()

`black_squares_llewis`.`car` (66900 tuples)
`black_squares_llewis`.`car_available` (4080900 tuples)
Proceed? [yes, No]: yes
Tables dropped.  Restart kernel.

In [12]:
@schema
class Car(dj.Manual):
    definition = """
    car_vin : varchar(60)
    ---
    -> Owner
    car_type : varchar(300)
    car_fuel_type : enum('regular', 'premium', 'mid-grade')
    car_number_seats : int
    car_trunk_size : int 
    mpg : decimal(6,2) 
    """

In [13]:
Car.insert(dict(key, car_vin=fake.bothify(text='#????##????######'),
            car_type=fake.vehicle_year_make_model_cat(),
            car_fuel_type=random.choice(("regular", "premium", "mid-grade")),
            car_number_seats= random.randint(1,8),
            car_trunk_size=random.randint(12,23),
            mpg=decimal.Decimal(random.randrange(2355,6555))/100) for key in Owner.fetch('KEY'))

In [14]:
Car()

*car_vin       owner_id       car_type       car_fuel_type  car_number_sea car_trunk_size mpg
+------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +-------+
0AmxO65tPfr830 4e5ccb0ed682f6 2018 Ford Tran premium        3              21             50.31
0BvvV98xGTD869 8b7e235182db33 1993 Chevrolet regular        4              20             27.00
0dhRP92VLiQ139 92562648e39149 2006 Pontiac S regular        2              21             47.22
0EGYX04mMzV282 33f6e96e9992ba 1999 MAZDA Pro regular        1              14             62.39
0EmyO21imba427 689ec0675893da 2016 Kia Soul  mid-grade      1              19             37.15
0EPFJ71Jskq082 21d6727af3e166 2009 Volvo V70 premium        1              15             24.53
0FjQy14YTxx250 c8de8fd8706f6d 2010 Lexus SC  mid-grade      7              20             31.88
0fTxe95CNhL442 032ae246147dc2 2005 Mitsubish regular        4              17             48.20
0hAch55Asge915 956b66c394ba20 2000 Oldsmobil regular        4              13             50.15
0HQTM59tjdK216 3d641c6e0456fd 2005 Hyundai S mid-grade      8              16             54.47
0jnYL15ZVgY928 d0bb552e10a12e 1997 Chrysler  regular        4              23             30.61
0klbF47trxg130 e897ac9bfd7bb3 1998 Honda CR- regular        1              22             39.85
   ...
 (Total: 223)

In [ ]:
Owner.drop()

In [11]:
@schema
class Owner(dj.Manual):
    definition = """
    owner_id : varchar(300)
    ---
    owner_first_name : varchar(30)
    owner_last_name : varchar(30)
    owner_date_of_birth : date
    owner_phone : varchar(60)
    owner_email : varchar(200)
    owner_address : varchar(200)
    
    """

In [ ]:
dir(fake)

In [ ]:
Owner.insert(dict(owner_id=fake.md5(), owner_first_name=fake.first_name(),
                 owner_last_name=fake.last_name(),
                 owner_date_of_birth=fake.date_between(end_date='-18y'),
                 owner_phone=fake.bothify(text='###-###-####'),
                 owner_email=fake.email(),
                 owner_address=' '.join((fake.street_address(),
                                        fake.state(),
                                        fake.city()))) for i in tqdm.tqdm(range(223)))

In [53]:
Owner()

*owner_id      owner_first_na owner_last_nam owner_date_of_ owner_phone    owner_email    owner_address
+------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+
032ae246147dc2 Kelly          Lewis          1999-04-27     469-462-1053   mark93@francis 38652 Kayla Mo
04fb48e3233bc4 Michael        Flowers        1999-07-11     063-656-6481   davidyang@gmai 1021 Dawn Driv
068992617e836e Richard        Garrett        2002-02-25     250-995-0537   matthew31@whit 7375 Gerald Ex
0774475f5be20e Susan          Brown          2002-11-21     993-115-2793   owenslisa@yaho 86672 Sullivan
07b23f00193cc0 Shannon        Cooper         1998-04-26     229-581-5757   hpreston@kenne 358 Carmen Lak
085b545cc4ee97 Amanda         Poole          1994-08-31     639-211-7999   kathleenjackso 94852 Hill Har
0d19550d552cb2 Jennifer       Foster         2000-06-01     603-366-7779   nfitzgerald@gm 603 Ryan Lake
0db1b768d1c0b3 Joshua         Sweeney        1997-12-17     868-538-8991   dmckenzie@belt 207 Roberto La
0e02b9144fa5e3 Mary           Donaldson      2002-09-01     727-424-6229   cameron83@yaho 950 Benjamin M
0f4c7d152f94a8 Matthew        Smith          1995-08-04     415-037-4497   aconner@gonzal 875 Diana Burg
0f5b20cdbf0958 Joyce          Spencer        1992-06-10     463-049-9136   hartmanpaige@h 828 Martha Sho
0fd83160ea21a9 Catherine      Morrison       2002-07-27     200-985-4867   hernandezjason 371 Melissa Wa
   ...
 (Total: 223)

In [59]:
CarAvailable.drop()

`black_squares_llewis`.`car_available` (4080900 tuples)
Proceed? [yes, No]: yes
Tables dropped.  Restart kernel.

In [15]:
@schema
class CarAvailable(dj.Manual):
    definition = """
    -> Car
    car_available_date : date
    ---
    car_price : decimal(6, 2)
    free_miles_per_day : int
    extra_price_per_mile : decimal(6,2)
    """

In [17]:
start_date = datetime.date(2021, 12, 1)
days = 61


for day in tqdm.tqdm(range(days)):
    car_price = random.randint(40, 350)
    free_miles=random.randint(45,60)
    extra_per_mile=random.randint(20, 40)
    CarAvailable.insert(dict(key, 
             car_available_date=start_date + datetime.timedelta(days=day), 
             car_price=car_price,
             free_miles_per_day=free_miles,
             extra_price_per_mile=extra_per_mile) for key in Car.fetch('KEY'))

100%|██████████| 61/61 [00:27<00:00,  2.22it/s]

In [18]:
CarAvailable()

*car_vin       *car_available car_price     free_miles_per extra_price_pe
+------------+ +------------+ +-----------+ +------------+ +------------+
0AmxO65tPfr830 2021-12-01     278.00        60             32.00
0AmxO65tPfr830 2021-12-02     301.00        45             25.00
0AmxO65tPfr830 2021-12-03     275.00        54             32.00
0AmxO65tPfr830 2021-12-04     184.00        58             27.00
0AmxO65tPfr830 2021-12-05     318.00        52             24.00
0AmxO65tPfr830 2021-12-06     101.00        48             21.00
0AmxO65tPfr830 2021-12-07     205.00        59             32.00
0AmxO65tPfr830 2021-12-08     189.00        47             32.00
0AmxO65tPfr830 2021-12-09     108.00        45             27.00
0AmxO65tPfr830 2021-12-10     270.00        58             29.00
0AmxO65tPfr830 2021-12-11     217.00        57             36.00
0AmxO65tPfr830 2021-12-12     271.00        53             35.00
   ...
 (Total: 13603)

In [ ]:
@schema 
class Driver(dj.Manual):
    definition = """
    driver_id : int 
    ---
    driver_first_name : varchar(60)
    driver_last_name : varchar(60)
    drivers_license_number : varchar(30)
    sex : enum('male', 'female')
    driver_date_of_birth : date
    driver_phone : char(15)
    driver_email : varchar(30)
    driver_address : varchar(60)
    """

In [ ]:
Driver()

In [ ]:
@schema 
class Reservation(dj.Manual):
    definition = """
    -> CarAvailable
    ---
    -> Driver
    credit_card : varchar(80)
    """

In [ ]:
Reservation()

In [ ]:
@schema
class CheckIn(dj.Manual):
    definition = """
    -> Reservation
    """

In [ ]:
CheckIn()

In [ ]:
@schema
class CheckOut(dj.Manual):
    definition = """
    -> CheckIn
    """

In [ ]:
CheckOut()